# Mode A - Ultra Light
CTRL+1 no-osd change-list glsl-shaders set "~~/shaders/Anime4K_Restore_CNN_UL.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_VL.glsl"; show-text "Anime4K: Mode A (VL)"

# Mode B - Soft Ultra Light
CTRL+2 no-osd change-list glsl-shaders set "~~/shaders/Anime4K_Restore_CNN_Soft_UL.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_VL.glsl"; show-text "Anime4K: Mode B (VL)"

# Clear
CTRL+0 no-osd change-list glsl-shaders clr ""; show-text "Shaders Cleared"
# Clear all
CTRL+0 no-osd change-list glsl-shaders clr ""; set interpolation no; show-text "Shaders & Interpolation Cleared"

# LUTs
k script-binding cycle-luts
K script-binding clear-lut
