###########
# General #
###########
input-ipc-server=/tmp/mpvsocket
# Standard GPU output, gpu-next is why you're seeing blue.
script-opts=mpris-arturl=file:///tmp/mpv-thumb.png
vo=gpu
# OpenGL is the most stable path for Intel+NVIDIA on Linux.
gpu-api=opengl
# Crucial: Hardware decoding must be explicitly set for Linux.
hwdec=vaapi
reset-on-next-file=all
framedrop=vo
af=lavfi=[loudnorm=I=-16:TP=-3:LRA=4]

######
# UI #
######
border=no
msg-color=yes
term-osd-bar=yes
cursor-autohide=1000

############
# Playback #
############
# DO NOT use display-resample. It is killing your thermal head-room.
video-sync=audio
interpolation=no
deinterlace=no

##############
# Colorspace #
##############
# Let the driver decide. Stop the manual math.
target-prim=auto
target-trc=auto
video-output-levels=auto
##########
# Dither #
##########
# Off. Your screen isn't good enough to notice anyway.
dither=no

#############
# Debanding #
#############
# Off. This is a massive GPU cycle hog.
deband=no

#########################
# Performance Profiles  #
#########################

[high-res-performance]
profile-cond=width >= 1919 or height >= 1079
# Use the fastest, coldest scaling possible.
scale=bilinear
cscale=bilinear
dscale=bilinear
# Ensure no high-end shaders are lurking.
glsl-shaders=""
